### ISSUE TITLE
Can't get it to work, dependencies are installed

### ISSUE THREAD

**Issue by Razer0123** [FxPape/fdclct#5]
Tried to run the example command to make c red, this is what i get

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/alessandro/Scrivania/fdclct-master/drevo/__main__.py", line 57, in <module>
    main()
  File "/home/alessandro/Scrivania/fdclct-master/drevo/__main__.py", line 34, in main
    lightctl = keylights.Keylights()
  File "/home/alessandro/Scrivania/fdclct-master/drevo/keylights.py", line 28, in __init__
    self.adapter = usblinux.Usblinux()
  File "/home/alessandro/Scrivania/fdclct-master/drevo/usblinux.py", line 17, in __init__
    "Keyboard not present or insufficient permissions")
ValueError: Keyboard not present or insufficient permissions
Exception ignored in: <bound method Usblinux.__del__ of <drevo.usblinux.Usblinux object at 0x7f76fc83bf60>>
Traceback (most recent call last):
  File "/home/alessandro/Scrivania/fdclct-master/drevo/usblinux.py", line 49, in __del__
    usb.util.dispose_resources(self.dev)
AttributeError: 'Usblinux' object has no attribute 'dev'
```

**Comment by userx14** [comment]
I'm not the author of this repo, but according to the error message you get, the code fails because dev is none (the search for the usb device was not sucessful) in this part of the code:

https://github.com/FxPape/fdclct/blob/f0b0799cea76f7c0d402f3dd514dc3a4a85089c8/drevo/usblinux.py#L10

The script tries to find the usb device with a specific vendor and device id and does not suceed in doing so.

Have you started the script with root priviledges or added an udev rule so that the script has access to the usb device? 

Can you verfiy that the command `lsusb` reports a device with id's 0x0483 for vendor, and 0x4010 for product if you have the keyboard connected?

**Comment by dnettoRaw** [comment]
same here
wen i run `lsusb` i can't see any a device with id's 0x0483 for vendor, and 0x4010 for product
